#!/usr/bin/env bash
# Story 10.8 (#137 B3). Produce the mTLS material the audit webhook
# needs, in one place, so both sides of the handshake agree.
#
# The receiver verifies the apiserver's CLIENT certificate against
# auditWebhook.clusterCAData (internal/collector/audit/audit.go,
# ClientCAs) and additionally pins its CN. AUDIT.md used to sign the
# client cert with a private audit CA while telling the operator to set
# clusterCAData to the cluster's own root CA, so the receiver rejected
# every apiserver connection. One CA signs both certificates here, and
# that CA is what clusterCAData carries.
#
# Usage:
#   hack/audit-webhook-certs.sh <out-dir> [server-name ...]
#
# Each server name is added to the receiver's serving certificate: a DNS
# name (the Service FQDN) or an IP address (a fixed ClusterIP, or
# 127.0.0.1 when the receiver is published on the node through
# auditWebhook.hostPort). With none given, the kind defaults are used.
#
# It writes audit-ca.crt, audit-server.crt/key, audit-client.crt/key and
# a values file (audit-webhook-values.yaml) with every field already
# base64-encoded on one line, ready for `helm install -f`.
set -euo pipefail

if [ "$#" -lt 1 ]; then
    echo "usage: $0 <out-dir> [server-name ...]" >&2
    exit 2
fi

out_dir="$1"
shift
names=("$@")
if [ "${#names[@]}" -eq 0 ]; then
    names=("olaitan-audit-webhook.olaitan.svc.cluster.local" "olaitan-audit-webhook.olaitan.svc" "127.0.0.1")
fi

# CN the receiver pins on the apiserver's client certificate. It must
# match auditWebhook.clientCNAllow (default kube-apiserver).
client_cn="${AUDIT_CLIENT_CN:-kube-apiserver}"
days="${AUDIT_CERT_DAYS:-365}"

mkdir -p "$out_dir"
cd "$out_dir"

san=""
for n in "${names[@]}"; do
    if printf '%s' "$n" | grep -Eq '^[0-9]+(\.[0-9]+){3}$'; then
        san="${san}${san:+,}IP:${n}"
    else
        san="${san}${san:+,}DNS:${n}"
    fi
done

# One CA for both directions. RSA, not Ed25519: kube-apiserver's audit
# webhook client and older cluster tooling still reject Ed25519 chains.
openssl req -x509 -newkey rsa:2048 -nodes -days "$days" \
    -subj "/CN=olaitan-audit-ca" -keyout audit-ca.key -out audit-ca.crt 2>/dev/null

# Receiver serving certificate, with a SAN for every address the
# apiserver may dial (auditWebhook.serverAddress).
openssl req -newkey rsa:2048 -nodes -subj "/CN=olaitan-audit-webhook" \
    -keyout audit-server.key -out audit-server.csr 2>/dev/null
printf 'subjectAltName=%s\nextendedKeyUsage=serverAuth\nbasicConstraints=CA:FALSE\n' "$san" > audit-server.ext
openssl x509 -req -in audit-server.csr -CA audit-ca.crt -CAkey audit-ca.key \
    -CAcreateserial -days "$days" -extfile audit-server.ext -out audit-server.crt 2>/dev/null

# The apiserver's client certificate, signed by the SAME CA the receiver
# verifies clients against, with the CN the receiver pins.
openssl req -newkey rsa:2048 -nodes -subj "/CN=${client_cn}" \
    -keyout audit-client.key -out audit-client.csr 2>/dev/null
printf 'extendedKeyUsage=clientAuth\nbasicConstraints=CA:FALSE\n' > audit-client.ext
openssl x509 -req -in audit-client.csr -CA audit-ca.crt -CAkey audit-ca.key \
    -CAcreateserial -days "$days" -extfile audit-client.ext -out audit-client.crt 2>/dev/null

b64() { base64 -w0 "$1"; }

cat > audit-webhook-values.yaml <<EOF
# Generated by hack/audit-webhook-certs.sh. Pass with: helm install -f
# this file. caBundle is the CA the apiserver trusts for the receiver's
# serving cert; clusterCAData is the CA the receiver verifies the
# apiserver's client cert against. Story 10.8: they are the same CA, and
# the client cert below is signed by it.
auditWebhook:
  enabled: true
  caBundle: "$(b64 audit-ca.crt)"
  clusterCAData: "$(b64 audit-ca.crt)"
  servingCert: "$(b64 audit-server.crt)"
  servingKey: "$(b64 audit-server.key)"
  apiserverClientCert: "$(b64 audit-client.crt)"
  apiserverClientKey: "$(b64 audit-client.key)"
EOF

rm -f audit-server.csr audit-client.csr audit-server.ext audit-client.ext

echo "wrote $(pwd)/audit-webhook-values.yaml"
echo "serving-cert names: ${names[*]}"
echo "client CN: ${client_cn}"
