#!/usr/bin/env bash
# Story 10.5. Bring up the kind-full reference cluster: the one cluster
# where all five Olaitan sources run at once, with Falco ON and Calico
# enforcing NetworkPolicy for real.
#
# Usage:
#   hack/install-full-kind.sh <out-dir>
#
# <out-dir> receives private key material and MUST be outside this
# repository. Point it at a scratch directory.
#
# Environment overrides:
#   CLUSTER_NAME  kind cluster name              (default olaitan-full)
#   WORKERS       worker nodes to create         (default: as written in
#                 hack/kind-full.yaml, which is 2). Set WORKERS=1 on a
#                 host under ~16GB: the profile still installs, but
#                 cross-node Calico flows stop being exercised.
#   RELEASE       helm release name              (default olaitan)
#   NAMESPACE     target namespace               (default "default",
#                 matching the e2e suite; see below)
#   plus every override hack/install-calico-kind.sh accepts
#   (KIND_NODE_IMAGE, CALICO_VERSION, KUBECONFIG, GOLDMANE_TIMEOUT).
#
# Why this script exists rather than a documented sequence of commands:
# the kube-apiserver on kind is a static pod that refuses to start when
# its audit policy or webhook kubeconfig is missing. Both files must
# therefore be on disk BEFORE `kind create cluster` runs, which means the
# audit CA has to be generated before any node exists. That ordering is
# not something an operator should have to rediscover.
set -euo pipefail
umask 077

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"

die() { echo "$0: $*" >&2; exit 2; }
info() { echo "==> $*"; }

[ "$#" -ge 1 ] || die "usage: $0 <out-dir>"
out_dir="$1"

cluster_name="${CLUSTER_NAME:-olaitan-full}"
release="${RELEASE:-olaitan}"
# "default", not "olaitan": the e2e suite hardcodes defaultNamespace =
# "default" (tests/e2e/rs_smoke_test.go) with no env override, and the AC1
# test lives in that suite. A profile that installs somewhere else cannot be
# asserted by the suite that is supposed to gate it.
namespace="${NAMESPACE:-default}"

for bin in kind kubectl helm openssl; do
    command -v "$bin" >/dev/null 2>&1 || die "missing required binary: ${bin}"
done

case "$(readlink -f "$out_dir" 2>/dev/null || echo "$out_dir")" in
    "${repo_root}"|"${repo_root}"/*)
        die "<out-dir> is inside the repository (${out_dir}). It receives a private key that can authenticate to the apiserver audit path; keep it out of any working tree."
        ;;
esac

mkdir -p "$out_dir"

# --- 1. audit material, BEFORE the cluster exists ----------------------
# Mounted into the control-plane node at /etc/kubernetes/audit by the
# extraMounts block in hack/kind-full.yaml. The path is relative to the
# repo root there, so this location is load-bearing: moving it means
# editing both files.
audit_mount="${repo_root}/hack/.audit-full"
cert_dir="${out_dir}/audit-certs"

if [ -e "${cert_dir}/audit-ca.crt" ]; then
    info "reusing the audit CA already in ${cert_dir}"
else
    info "generating audit mTLS material for 127.0.0.1"
    # 127.0.0.1 because the apiserver dials its own node's loopback
    # through auditWebhook.hostPort. See values-full.yaml for why a node
    # IP cannot be used here.
    "${script_dir}/audit-webhook-certs.sh" "$cert_dir" 127.0.0.1 \
        "${release}-audit-webhook.${namespace}.svc"
fi

# Overwrite in place; do NOT rm -rf. On a re-run against an existing
# cluster this directory is already bind-mounted into the control-plane
# node at /etc/kubernetes/audit. Removing and recreating it replaces the
# inode, so the node's mount keeps pointing at the deleted one and the
# apiserver fails to find its policy on the next restart, with a message
# that blames the file rather than the mount.
mkdir -p "$audit_mount"

# The apiserver reads the policy as root but the file is bind-mounted
# read-only; 0644 matches what AUDIT.md prescribes for the kubeadm path.
cp "${repo_root}/config/audit-policy-default.yaml" "${audit_mount}/policy.yaml"
chmod 0644 "${audit_mount}/policy.yaml"

b64() { base64 -w0 < "$1"; }

cat > "${audit_mount}/webhook-kubeconfig.yaml" <<KUBECONFIG
# Generated by hack/install-full-kind.sh. Do not edit.
#
# The kube-apiserver presents the client certificate below to the Olaitan
# audit receiver and verifies the receiver against certificate-authority-data.
# One CA signs both sides (hack/audit-webhook-certs.sh); see that script
# for why two CAs silently rejected every connection.
apiVersion: v1
kind: Config
clusters:
  - name: olaitan-audit
    cluster:
      # The /audit path is load-bearing. The receiver muxes /audit and
      # /healthz (internal/collector/audit/audit.go); a bare host:port
      # returns 404 and the apiserver reports "the server could not find
      # the requested resource" while dropping every batch, with the TCP
      # connection succeeding the whole time. Note auditWebhook.serverAddress
      # in values.yaml is deliberately path-less: the chart appends the
      # path when it builds the in-cluster kubeconfig, so a hand-written
      # kubeconfig like this one has to add it itself.
      server: https://127.0.0.1:8443/audit
      certificate-authority-data: $(b64 "${cert_dir}/audit-ca.crt")
users:
  - name: kube-apiserver
    user:
      client-certificate-data: $(b64 "${cert_dir}/audit-client.crt")
      client-key-data: $(b64 "${cert_dir}/audit-client.key")
contexts:
  - name: olaitan-audit
    context:
      cluster: olaitan-audit
      user: kube-apiserver
current-context: olaitan-audit
KUBECONFIG
chmod 0600 "${audit_mount}/webhook-kubeconfig.yaml"
info "wrote ${audit_mount}/{policy.yaml,webhook-kubeconfig.yaml}"

# --- 1b. applog admission webhook serving cert -------------------------
# The applog sidecar is injected by a MutatingWebhookConfiguration, so the
# apiserver dials it over TLS and the chart requires servingCert/servingKey
# plus the caBundle it distributes. Unlike the audit webhook, no script in
# the repo generates this material, and the chart fails render without it
# (templates/applog-webhook-tls-secret.yaml). cert-manager is the other
# supported route (applogSidecar.tls.certManagerEnabled=true) and is the
# better answer for a real cluster; a self-signed pair keeps kind-full
# installable with no extra operator.
applog_dir="${out_dir}/applog-certs"
applog_svc="${release}-applog-injector.${namespace}.svc"

if [ -e "${applog_dir}/tls.crt" ]; then
    info "reusing the applog webhook cert already in ${applog_dir}"
else
    info "generating applog webhook CA + serving cert for ${applog_svc}"
    mkdir -p "$applog_dir"
    # A CA and a serving cert it signs, NOT one self-signed cert used as
    # its own caBundle. A self-signed cert carries CA:TRUE but, once
    # keyUsage is pinned to digitalSignature+keyEncipherment for serverAuth,
    # it lacks keyCertSign; Go's crypto/x509 (which kube-apiserver uses)
    # then refuses to treat it as a CA and the TLS handshake fails. The
    # MutatingWebhookConfiguration ships failurePolicy: Ignore, so that
    # failure is SILENT: pods are admitted with no sidecar, no error and
    # no admission request in the injector log. Two certs cost nothing and
    # remove the whole failure mode.
    openssl req -x509 -newkey rsa:2048 -nodes -days 365 \
        -keyout "${applog_dir}/ca.key" -out "${applog_dir}/ca.crt" \
        -subj "/CN=olaitan-applog-injector-ca" \
        -addext "basicConstraints=critical,CA:TRUE" \
        -addext "keyUsage=critical,keyCertSign,cRLSign" \
        >/dev/null 2>&1

    openssl req -newkey rsa:2048 -nodes \
        -keyout "${applog_dir}/tls.key" -out "${applog_dir}/tls.csr" \
        -subj "/CN=${applog_svc}" >/dev/null 2>&1

    openssl x509 -req -in "${applog_dir}/tls.csr" \
        -CA "${applog_dir}/ca.crt" -CAkey "${applog_dir}/ca.key" \
        -CAcreateserial -days 365 -out "${applog_dir}/tls.crt" \
        -extfile <(printf '%s\n' \
            "subjectAltName=DNS:${applog_svc},DNS:${applog_svc}.cluster.local,DNS:${release}-applog-injector.${namespace}" \
            "keyUsage=critical,digitalSignature,keyEncipherment" \
            "extendedKeyUsage=serverAuth" \
            "basicConstraints=critical,CA:FALSE") \
        >/dev/null 2>&1
fi

cat > "${applog_dir}/applog-values.yaml" <<APPLOG
# Generated by hack/install-full-kind.sh. Do not edit, do not commit.
applogSidecar:
  tls:
    certManagerEnabled: false
    servingCert: "$(b64 "${applog_dir}/tls.crt")"
    servingKey: "$(b64 "${applog_dir}/tls.key")"
    caBundle: "$(b64 "${applog_dir}/ca.crt")"
APPLOG
chmod 0600 "${applog_dir}/applog-values.yaml"

# --- 2. kind config, optionally trimmed to WORKERS ---------------------
kind_config="${repo_root}/hack/kind-full.yaml"
if [ -n "${WORKERS:-}" ]; then
    [ "$WORKERS" -ge 0 ] 2>/dev/null || die "WORKERS must be a non-negative integer, got \"${WORKERS}\""
    trimmed="${out_dir}/kind-full-${WORKERS}w.yaml"
    python3 - "$kind_config" "$trimmed" "$WORKERS" <<'PY'
import sys, yaml
src, dst, workers = sys.argv[1], sys.argv[2], int(sys.argv[3])
doc = yaml.safe_load(open(src))
cp = [n for n in doc["nodes"] if n["role"] == "control-plane"]
w  = [n for n in doc["nodes"] if n["role"] == "worker"]
if workers > len(w):
    w = w + [{"role": "worker"}] * (workers - len(w))
doc["nodes"] = cp + w[:workers]
yaml.safe_dump(doc, open(dst, "w"), sort_keys=False)
PY
    kind_config="$trimmed"
    info "using ${WORKERS} worker node(s) (${kind_config})"
fi

# --- 3. cluster + Calico -----------------------------------------------
# Reuses the Story 10.11 bring-up rather than duplicating it; KIND_CONFIG
# is the override added for exactly this.
info "creating cluster ${cluster_name} and installing Calico"
KIND_CONFIG="$kind_config" CLUSTER_NAME="$cluster_name" \
    "${script_dir}/install-calico-kind.sh" "${out_dir}/calico"

# --- 4. the chart ------------------------------------------------------
info "installing ${release} with the full profile"
helm upgrade --install "$release" "${repo_root}/deploy/helm/olaitan" \
    --namespace "$namespace" --create-namespace \
    -f "${repo_root}/deploy/helm/olaitan/values-full.yaml" \
    -f "${out_dir}/calico/calico-values.yaml" \
    -f "${cert_dir}/audit-webhook-values.yaml" \
    -f "${applog_dir}/applog-values.yaml" \
    --wait --timeout 15m

info "installed. all five sources should report healthy within 5 minutes:"
info "  kubectl -n ${namespace} port-forward ds/${release}-collector 9093:9090"
info "  curl -s localhost:9093/metrics | grep olaitan_source_healthy"
