#!/usr/bin/env bash
# Story 12.4: render the chart's default install into one file that
# `kubectl apply -f` installs, for people who do not use helm.
#
#   hack/render-install-manifest.sh <chart dir or packaged .tgz> <out file>
#
# The release workflow runs this on the chart it just packaged (stamped
# version, appVersion and image digest), and attaches the result to the
# GitHub release as install.yaml. The helm test suite
# (TestInstallManifestIsOneApplyableFile) runs it on a stamped copy of the
# chart on every CI run, so a break shows up before a release does.
#
# What it adds to a plain `helm template`, and why:
#   - a Namespace object first: `helm install --create-namespace` makes the
#     namespace, kubectl apply only makes what the file holds;
#   - nats.namespaceOverride: the NATS subchart renders its objects with no
#     namespace at all, and kubectl apply would put them in the context's
#     namespace (usually `default`);
#   - --skip-tests: the NATS `helm test` Pod is a hook; kubectl would run it
#     as an ordinary Pod that completes and is never Ready.
# Nothing else is set: the file is the chart's defaults.
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 <chart dir or .tgz> <out file>" >&2
  exit 2
fi
chart=$1 out=$2
# The README requires this namespace for the helm path too: the agent's
# default excluded_namespaces list contains it.
ns=olaitan

[[ -e "$chart" ]] || { echo "no chart at '${chart}'" >&2; exit 1; }

version="$(helm show chart "$chart" | awk '/^version:/ { print $2; exit }')"
[[ -n "$version" ]] || { echo "cannot read the chart version of '${chart}'" >&2; exit 1; }

rendered="$(helm template olaitan "$chart" \
  --namespace "$ns" \
  --skip-tests \
  --set "nats.namespaceOverride=${ns}")"
grep -q '^kind: ' <<<"$rendered" || { echo "helm template rendered no objects" >&2; exit 1; }

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
{
  echo "# Olaitan install manifest: chart olaitan ${version}, default values."
  echo "# Generated by hack/render-install-manifest.sh in the release workflow."
  echo "# Do not edit; install with:"
  echo "#   kubectl apply -f install.yaml"
  echo "---"
  echo "apiVersion: v1"
  echo "kind: Namespace"
  echo "metadata:"
  echo "  name: ${ns}"
  printf '%s\n' "$rendered"
} > "$tmp"
mv "$tmp" "$out"
trap - EXIT
