#!/usr/bin/env bash
# Story 12.4: render the chart's default install into one file that
# `kubectl apply -f` installs, for people who do not use helm.
#
#   hack/render-install-manifest.sh <chart dir or packaged .tgz> <out file>
#
# The release workflow runs this on the chart it just packaged (stamped
# version, appVersion and image digest), and attaches the result to the
# GitHub release as install.yaml. The helm test suite
# (TestInstallManifestIsOneApplyableFile) runs it on a stamped copy of the
# chart on every CI run, so a break shows up before a release does.
#
# What it adds to a plain `helm template`, and why:
#   - a Namespace object first: `helm install --create-namespace` makes the
#     namespace, kubectl apply only makes what the file holds;
#   - nats.namespaceOverride: the NATS subchart renders its objects with no
#     namespace at all, and kubectl apply would put them in the context's
#     namespace (usually `default`);
#   - --skip-tests: the NATS `helm test` Pod is a hook; kubectl would run it
#     as an ordinary Pod that completes and is never Ready.
# Nothing else is set: the file is the chart's defaults.
#
# What it removes, and why (Story 12.4, D5):
#   - the chart's Secret olaitan-secrets. templates/secret.yaml generates the
#     bundled Redis password and the Falco ingest token when it cannot look
#     up a live Secret, which under `helm template` is always. In a release
#     asset that would be one public value shared by every install: anyone
#     who reads the file could wipe suspicion state in Redis, or forge Falco
#     alerts, from any pod the CNI does not stop. The workloads still read
#     that Secret; the header below (and the README) create it per install
#     with fresh random values before the apply. The render fails if the
#     Secret is missing or found more than once, so a rename in the chart
#     cannot quietly ship the credentials again.
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 <chart dir or .tgz> <out file>" >&2
  exit 2
fi
chart=$1 out=$2
# The README requires this namespace for the helm path too: the agent's
# default excluded_namespaces list contains it.
ns=olaitan
secret=olaitan-secrets

[[ -e "$chart" ]] || { echo "no chart at '${chart}'" >&2; exit 1; }

version="$(helm show chart "$chart" | awk '/^version:/ { print $2; exit }')"
[[ -n "$version" ]] || { echo "cannot read the chart version of '${chart}'" >&2; exit 1; }

rendered="$(helm template olaitan "$chart" \
  --namespace "$ns" \
  --skip-tests \
  --set "nats.namespaceOverride=${ns}")"
grep -q '^kind: ' <<<"$rendered" || { echo "helm template rendered no objects" >&2; exit 1; }

# Drop the one document that is Secret/olaitan-secrets. helm template
# starts every document with a "---" line.
stripped="$(awk -v name="$secret" '
  function flush() {
    if (doc != "" && !(is_secret && is_named)) printf "%s", doc
    if (is_secret && is_named) dropped++
    doc = ""; is_secret = 0; is_named = 0
  }
  /^---$/ { flush() }
  { doc = doc $0 "\n" }
  /^kind: Secret$/ { is_secret = 1 }
  $0 == "  name: " name { is_named = 1 }
  END { flush(); print "#dropped=" dropped + 0 }
' <<<"$rendered")"
dropped="$(tail -n 1 <<<"$stripped")"
[[ "$dropped" == "#dropped=1" ]] \
  || { echo "expected exactly one Secret/${secret} in the render, removed ${dropped#\#dropped=}" >&2; exit 1; }
stripped="$(sed '$d' <<<"$stripped")"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
{
  cat <<EOF
# Olaitan install manifest: chart olaitan ${version}, default values.
# Generated by hack/render-install-manifest.sh in the release workflow.
# Do not edit.
#
# This file holds no credentials. Create the namespace and the Secret the
# workloads read once, with fresh random values, then apply the file:
#
#   kubectl create namespace ${ns} --save-config
#   kubectl create secret generic ${secret} -n ${ns} \\
#     --from-literal=redis-password="\$(openssl rand -hex 32)" \\
#     --from-literal=falco-http-token="\$(openssl rand -hex 32)" \\
#     --from-literal=llm-api-key=
#   kubectl apply -f install.yaml
#
# Applying this file (again, or a newer release's) never touches
# ${secret}: it is not in the file. After applying a newer release, restart
# every workload so all of them start on the same Secret and config:
#
#   kubectl -n ${ns} rollout restart daemonset,deployment,statefulset
#
# API server egress: NetworkPolicy "olaitan" lets the collector and the
# aggregator reach only 10.96.0.1 (the kubeadm Service IP) on 443 and 6443,
# because a rendered file cannot look the real address up. That is not
# enough on k3s (Service IP 10.43.0.1), on minikube (API server on 8443),
# or on Calico or Cilium, which match egress after the Service IP is
# translated to the API server's own address. There, allow the real
# addresses after the apply (read them with
# kubectl get endpointslice -n default kubernetes):
#
#   port=\$(kubectl get endpointslice -n default kubernetes -o jsonpath='{.ports[0].port}')
#   for ip in \$(kubectl get service -n default kubernetes -o jsonpath='{.spec.clusterIP}') \\
#             \$(kubectl get endpointslice -n default kubernetes -o jsonpath='{.endpoints[*].addresses[*]}'); do
#     kubectl -n ${ns} patch networkpolicy olaitan --type=json -p \\
#       "[{\"op\":\"add\",\"path\":\"/spec/egress/-\",\"value\":{\"to\":[{\"ipBlock\":{\"cidr\":\"\${ip}/32\"}}],\"ports\":[{\"protocol\":\"TCP\",\"port\":443},{\"protocol\":\"TCP\",\"port\":\${port}}]}}]"
#   done
#
# Run it again after applying a newer release. The README has the details.
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${ns}
EOF
  printf '%s\n' "$stripped"
} > "$tmp"
mv "$tmp" "$out"
trap - EXIT
