// Package metrics exposes the unified Prometheus collection surface for
// every Olaitan process. Story 1.12 introduces it as the binding point
// for FR8 (per-source health gauge) and FR50 (every Olaitan process
// exposes Prometheus metrics on :9090/metrics).
//
// Why a dedicated package rather than reusing internal/health:
// architecture.md:374 places metrics on :9090/metrics, separate from
// the :8080/healthz kubelet probe surface served by internal/health.
// Bundling them on one port would force kubelet to inherit Prometheus
// scrape latency, which kubelet's probe SLO cannot tolerate. Operators
// also benefit from being able to apply different NetworkPolicy ingress
// rules to the kubelet surface (cluster-local) and the metrics surface
// (Prometheus scrape namespace).
//
// Registry isolation (guardrail 25): the package never touches the
// prometheus.DefaultRegisterer. Every Registry is constructed via
// NewRegistry() so tests are order-independent and future surfaces
// (debug exporters, sidecar exporters) can land without colliding on
// metric names.
//
// Reader-side counters (guardrail 26): every per-adapter counter is
// registered via prometheus.NewCounterFunc reading from an existing
// in-process atomic counter on the adapter. The metrics package never
// owns a writeable counter that the adapter increments; the adapter's
// atomic remains the single source of truth and there is no duplicate
// state to synchronise.
//
// Mandatory endpoint (guardrail 27): config.Validate rejects an empty
// metrics.address. The FR50 surface is not optional; silently degrading
// to "no metrics" would let an operator deploy an unobservable agent
// that still answers the kubelet probe.
package metrics

import (
	"errors"
	"fmt"
	"net/http"
	"sync"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"

	"github.com/olokotoh/olaitan/internal/sourcehealth"
)

// ErrNilRegistry is returned when a method is called on a nil *Registry.
var ErrNilRegistry = errors.New("metrics: nil registry")

// Registry wraps a prometheus.Registry plus the small amount of
// coordination state needed to register per-source adapter readers and
// the posture counters. A zero Registry is not usable; construct via
// NewRegistry. Methods are safe for concurrent use; the underlying
// prometheus.Registry already serialises Register calls, and our own
// state guards against double-registration of the same source.
type Registry struct {
	reg *prometheus.Registry

	mu      sync.Mutex
	sources map[string]struct{}
}

// NewRegistry constructs an isolated Registry. The returned value never
// shares state with prometheus.DefaultRegisterer; per-process callers
// must hold on to the returned pointer and pass it explicitly to every
// Register* helper.
func NewRegistry() *Registry {
	return &Registry{
		reg:     prometheus.NewRegistry(),
		sources: make(map[string]struct{}),
	}
}

// Handler returns an http.Handler suitable for mounting at /metrics on
// an http.Server. The handler is generated by promhttp.HandlerFor
// against this Registry's internal *prometheus.Registry, so it picks up
// every metric registered against this Registry and only those.
func (r *Registry) Handler() http.Handler {
	if r == nil {
		// Empty 404 surface keeps a nil-Registry from panicking when
		// wired into a router; the configured server should never reach
		// this branch because Server.New rejects a nil Registry.
		return http.NotFoundHandler()
	}
	return promhttp.HandlerFor(r.reg, promhttp.HandlerOpts{})
}

// Gatherer exposes the underlying prometheus.Gatherer. Tests use this
// to drive prometheus.testutil and promlint against the live registry
// without going through HTTP.
func (r *Registry) Gatherer() prometheus.Gatherer {
	if r == nil {
		return nil
	}
	return r.reg
}

// RegisterAdapter binds a single streaming source adapter to the
// Prometheus surface. It registers two metrics keyed on the source
// label:
//
//   - olaitan_source_healthy{source=<source>}  (gauge, 1.0=healthy, 0.0=unhealthy)
//   - olaitan_sensor_events_total{source=<source>}  (counter)
//
// healthy is the adapter's Health() Reader; eventsTotal is a getter
// returning the cumulative count of events the adapter has successfully
// published. Both readers must be O(1) and concurrent-safe; the
// Prometheus scrape thread calls them on every /metrics request.
//
// Returns an error if the same source has already been registered or
// if either argument is nil. The collector ring should call this once
// per adapter at startup.
func (r *Registry) RegisterAdapter(source string, healthy sourcehealth.Reader, eventsTotal func() int64) error {
	if r == nil {
		return ErrNilRegistry
	}
	if source == "" {
		return errors.New("metrics: empty source")
	}
	if healthy == nil {
		return fmt.Errorf("metrics: nil health reader for source %q", source)
	}
	if eventsTotal == nil {
		return fmt.Errorf("metrics: nil events-total getter for source %q", source)
	}

	r.mu.Lock()
	if _, dup := r.sources[source]; dup {
		r.mu.Unlock()
		return fmt.Errorf("metrics: source %q already registered", source)
	}
	r.sources[source] = struct{}{}
	r.mu.Unlock()

	healthyGauge := prometheus.NewGaugeFunc(
		prometheus.GaugeOpts{
			Name:        "olaitan_source_healthy",
			Help:        "Binary health gauge for an Olaitan sensor source; 1.0 means the upstream stream is producing events, 0.0 means it is disconnected or stalled (FR8).",
			ConstLabels: prometheus.Labels{"source": source},
		},
		func() float64 {
			ok, _ := healthy.Status()
			if ok {
				return 1.0
			}
			return 0.0
		},
	)
	if err := r.reg.Register(healthyGauge); err != nil {
		return fmt.Errorf("metrics: register source_healthy for %q: %w", source, err)
	}

	eventsCounter := prometheus.NewCounterFunc(
		prometheus.CounterOpts{
			Name:        "olaitan_sensor_events_total",
			Help:        "Cumulative count of normalised events the sensor adapter has successfully published to NATS JetStream (FR50).",
			ConstLabels: prometheus.Labels{"source": source},
		},
		func() float64 { return float64(eventsTotal()) },
	)
	if err := r.reg.Register(eventsCounter); err != nil {
		return fmt.Errorf("metrics: register sensor_events_total for %q: %w", source, err)
	}

	return nil
}

// PostureGetters carries the six posture-client counter readers
// landed in Story 1.11. The map keys must match exactly:
//
//	cache_hit, cache_miss, cache_bypass, api_errors, orphan_pods, unavailable
//
// Each value is the corresponding posture.Client getter; the Registry
// binds it to a Prometheus CounterFunc under
// olaitan_sensor_posture_<key>_total.
type PostureGetters = map[string]func() int64

// posturePromName maps the canonical short key to the Prometheus metric
// name and a one-line help string. Keys are exhaustive against AC4.
var posturePromName = []struct {
	key, name, help string
}{
	{"cache_hit", "olaitan_sensor_posture_cache_hit_total", "Cumulative posture-client cache hits (Story 1.11)."},
	{"cache_miss", "olaitan_sensor_posture_cache_miss_total", "Cumulative posture-client cache misses that fell through to a K8s API fetch (Story 1.11)."},
	{"cache_bypass", "olaitan_sensor_posture_cache_bypass_total", "Cumulative posture-client cache bypasses (WithBypassCache, Story 3.x LLM-eligible fresh-fetch path)."},
	{"api_errors", "olaitan_sensor_posture_api_errors_total", "Cumulative K8s API errors observed by the posture client, redacted to one of the four error classes (NFR15)."},
	{"orphan_pods", "olaitan_sensor_posture_orphan_pods_total", "Cumulative pods whose lineage could not be resolved, surfaced via the orphan-pod fallback workload identity."},
	{"unavailable", "olaitan_sensor_posture_unavailable_total", "Cumulative posture fetches that returned Unavailable=true to the caller (correlator hand-off for EvidencePackage.posture_unavailable)."},
}

// RegisterPostureCounters binds the six existing posture counters to
// the Prometheus surface using prometheus.NewCounterFunc. getters must
// contain a non-nil function under every key listed in
// posturePromName; missing or nil entries cause an error before any
// metric is registered (atomic semantics).
//
// The posture client is a single in-process instance (no per-source
// label), so cardinality stays bounded per NFR32.
func (r *Registry) RegisterPostureCounters(getters PostureGetters) error {
	if r == nil {
		return ErrNilRegistry
	}
	for _, p := range posturePromName {
		if fn := getters[p.key]; fn == nil {
			return fmt.Errorf("metrics: missing posture getter %q", p.key)
		}
	}
	for _, p := range posturePromName {
		fn := getters[p.key]
		c := prometheus.NewCounterFunc(
			prometheus.CounterOpts{Name: p.name, Help: p.help},
			func() float64 { return float64(fn()) },
		)
		if err := r.reg.Register(c); err != nil {
			return fmt.Errorf("metrics: register %s: %w", p.name, err)
		}
	}
	return nil
}

// RegisterPostureDisabled registers the olaitan_sensor_posture_disabled
// gauge with a constant value of 1.0. Use this when the operator has
// set posture.enabled=false so dashboards can distinguish "intentionally
// off" from "broken": consumers see a non-zero value for the disabled
// gauge but no posture_* counters appear at all.
func (r *Registry) RegisterPostureDisabled() error {
	if r == nil {
		return ErrNilRegistry
	}
	g := prometheus.NewGaugeFunc(
		prometheus.GaugeOpts{
			Name: "olaitan_sensor_posture_disabled",
			Help: "Set to 1.0 when posture.enabled=false; the six olaitan_sensor_posture_*_total counters are not registered in this case.",
		},
		func() float64 { return 1.0 },
	)
	if err := r.reg.Register(g); err != nil {
		return fmt.Errorf("metrics: register posture_disabled: %w", err)
	}
	return nil
}

// CounterReader is the structural-typed contract for an existing
// adapter-side atomic counter exposed as an int64 getter. Used by
// RegisterCounter for the non-source-keyed reader-only counters
// (audit reject reasons, CRI translate errors, CNI EOFs, applog drops).
type CounterReader = func() int64

// RegisterCounter binds a single source-keyed counter to the
// Prometheus surface. name is the fully-qualified metric name
// (e.g. olaitan_sensor_audit_rejected_total). source is the value
// applied to the "source" const-label; if empty, no source label is
// applied. labels carries any additional const labels (e.g. reason for
// the audit by-reason map). help is the one-line description.
//
// Returns an error if the metric is rejected by the registry (e.g.
// duplicate name+labels), or if get is nil.
func (r *Registry) RegisterCounter(name, source, help string, labels prometheus.Labels, get CounterReader) error {
	if r == nil {
		return ErrNilRegistry
	}
	if get == nil {
		return fmt.Errorf("metrics: nil getter for %q", name)
	}
	if name == "" {
		return errors.New("metrics: empty metric name")
	}

	merged := prometheus.Labels{}
	if source != "" {
		merged["source"] = source
	}
	for k, v := range labels {
		merged[k] = v
	}

	c := prometheus.NewCounterFunc(
		prometheus.CounterOpts{
			Name:        name,
			Help:        help,
			ConstLabels: merged,
		},
		func() float64 { return float64(get()) },
	)
	if err := r.reg.Register(c); err != nil {
		return fmt.Errorf("metrics: register %s: %w", name, err)
	}
	return nil
}

// GaugeReader is the structural-typed contract for an adapter-side
// gauge-valued counter that can decrease (resets to 0 on success,
// fluctuates with backlog, etc.). Use this for values that violate the
// Prometheus counter monotonicity contract.
type GaugeReader = func() int64

// RegisterGauge binds a gauge metric to the Prometheus surface. Use
// RegisterCounter for monotonically-increasing values; use RegisterGauge
// for values that can decrease such as consecutive-EOF counters that
// reset on a successful Recv (Copilot review CR2 on PR #21). Naming
// convention: gauges do NOT carry the _total suffix; counters do.
func (r *Registry) RegisterGauge(name, source, help string, labels prometheus.Labels, get GaugeReader) error {
	if r == nil {
		return ErrNilRegistry
	}
	if get == nil {
		return fmt.Errorf("metrics: nil getter for %q", name)
	}
	if name == "" {
		return errors.New("metrics: empty metric name")
	}

	merged := prometheus.Labels{}
	if source != "" {
		merged["source"] = source
	}
	for k, v := range labels {
		merged[k] = v
	}

	g := prometheus.NewGaugeFunc(
		prometheus.GaugeOpts{
			Name:        name,
			Help:        help,
			ConstLabels: merged,
		},
		func() float64 { return float64(get()) },
	)
	if err := r.reg.Register(g); err != nil {
		return fmt.Errorf("metrics: register %s: %w", name, err)
	}
	return nil
}
