// SPDX-License-Identifier: Apache-2.0

//
//Copyright (C) 2023 The Falco Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: outputs.proto

package falcopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The `request` message is the logical representation of the request model.
// It is the input of the `output.service` service.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_outputs_proto_rawDescGZIP(), []int{0}
}

// The `response` message is the representation of the output model.
// It contains all the elements that Falco emits in an output along with the
// definitions for priorities and source.
type Response struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Time     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Priority Priority               `protobuf:"varint,2,opt,name=priority,proto3,enum=falco.schema.Priority" json:"priority,omitempty"`
	// Deprecated: Marked as deprecated in outputs.proto.
	SourceDeprecated Source            `protobuf:"varint,3,opt,name=source_deprecated,json=sourceDeprecated,proto3,enum=falco.schema.Source" json:"source_deprecated,omitempty"`
	Rule             string            `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	Output           string            `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	OutputFields     map[string]string `protobuf:"bytes,6,rep,name=output_fields,json=outputFields,proto3" json:"output_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Hostname         string            `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Tags             []string          `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Source           string            `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_outputs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_outputs_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Response) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_EMERGENCY
}

// Deprecated: Marked as deprecated in outputs.proto.
func (x *Response) GetSourceDeprecated() Source {
	if x != nil {
		return x.SourceDeprecated
	}
	return Source_SYSCALL
}

func (x *Response) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *Response) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Response) GetOutputFields() map[string]string {
	if x != nil {
		return x.OutputFields
	}
	return nil
}

func (x *Response) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Response) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Response) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_outputs_proto protoreflect.FileDescriptor

const file_outputs_proto_rawDesc = "" +
	"\n" +
	"\routputs.proto\x12\rfalco.outputs\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fschema.proto\"\t\n" +
	"\arequest\"\xba\x03\n" +
	"\bresponse\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x122\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x16.falco.schema.priorityR\bpriority\x12E\n" +
	"\x11source_deprecated\x18\x03 \x01(\x0e2\x14.falco.schema.sourceB\x02\x18\x01R\x10sourceDeprecated\x12\x12\n" +
	"\x04rule\x18\x04 \x01(\tR\x04rule\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12N\n" +
	"\routput_fields\x18\x06 \x03(\v2).falco.outputs.response.OutputFieldsEntryR\foutputFields\x12\x1a\n" +
	"\bhostname\x18\a \x01(\tR\bhostname\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x1a?\n" +
	"\x11OutputFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x7f\n" +
	"\aservice\x12:\n" +
	"\x03sub\x12\x16.falco.outputs.request\x1a\x17.falco.outputs.response(\x010\x01\x128\n" +
	"\x03get\x12\x16.falco.outputs.request\x1a\x17.falco.outputs.response0\x01BFZDgithub.com/olokotoh/olaitan/internal/collector/falco/falcopb;falcopbb\x06proto3"

var (
	file_outputs_proto_rawDescOnce sync.Once
	file_outputs_proto_rawDescData []byte
)

func file_outputs_proto_rawDescGZIP() []byte {
	file_outputs_proto_rawDescOnce.Do(func() {
		file_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outputs_proto_rawDesc), len(file_outputs_proto_rawDesc)))
	})
	return file_outputs_proto_rawDescData
}

var file_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_outputs_proto_goTypes = []any{
	(*Request)(nil),               // 0: falco.outputs.request
	(*Response)(nil),              // 1: falco.outputs.response
	nil,                           // 2: falco.outputs.response.OutputFieldsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(Priority)(0),                 // 4: falco.schema.priority
	(Source)(0),                   // 5: falco.schema.source
}
var file_outputs_proto_depIdxs = []int32{
	3, // 0: falco.outputs.response.time:type_name -> google.protobuf.Timestamp
	4, // 1: falco.outputs.response.priority:type_name -> falco.schema.priority
	5, // 2: falco.outputs.response.source_deprecated:type_name -> falco.schema.source
	2, // 3: falco.outputs.response.output_fields:type_name -> falco.outputs.response.OutputFieldsEntry
	0, // 4: falco.outputs.service.sub:input_type -> falco.outputs.request
	0, // 5: falco.outputs.service.get:input_type -> falco.outputs.request
	1, // 6: falco.outputs.service.sub:output_type -> falco.outputs.response
	1, // 7: falco.outputs.service.get:output_type -> falco.outputs.response
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_outputs_proto_init() }
func file_outputs_proto_init() {
	if File_outputs_proto != nil {
		return
	}
	file_schema_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outputs_proto_rawDesc), len(file_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outputs_proto_goTypes,
		DependencyIndexes: file_outputs_proto_depIdxs,
		MessageInfos:      file_outputs_proto_msgTypes,
	}.Build()
	File_outputs_proto = out.File
	file_outputs_proto_goTypes = nil
	file_outputs_proto_depIdxs = nil
}
